version: "2"

volumes:
  mongo-data:
    driver: local

networks:
  NET_1:
    driver: bridge
  NET_2:
    driver: bridge

services:
  web:
    build: .
    container_name: web
    #network_mode: "myNET"
    networks:
      NET_1:
        aliases:
          - web_alias
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
        NODE_ENV: development
    depends_on:
        - mongo

  nginx:
    build: ./nginx/
    container_name: nginx
    networks:
      - NET_1
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    volumes_from:
      - web
    command: /bin/sh -c "nginx -g 'daemon off;'"


  mongo:
    image: mongo
    container_name: mongodb
    networks:
       - NET_1
       - NET_2
    ports:
       - "28001:27017"
    volumes:
       - mongo-data:/data/db

